# Generated by Django 6.0.4 on 2026-04-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('any', 'Any Level')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, choices=[('koshi', 'Koshi Province'), ('madhesh', 'Madhesh Province'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province'), ('remote', 'Remote / Work from Home'), ('nepal', 'Nepal (All)')], default='nepal', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, help_text='Monthly salary max (NPR)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, help_text='Monthly salary min (NPR)', null=True),
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_categories', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_alert', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='alerts', to='jobs.tag')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.tag'),
        ),
    ]
