# Generated by Django 6.0.4 on 2026-04-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_tag_job_experience_level_job_job_type_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('government', 'Government'), ('loksewa', 'Loksewa'), ('private', 'Private'), ('scholarship', 'Scholarship'), ('foreign', 'Foreign Employment'), ('internship', 'Internship'), ('opportunity', 'Opportunity')], default='government', max_length=20),
        ),
    ]
