# Generated by Django 6.0.4 on 2026-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('ad_type', models.CharField(choices=[('sidebar', 'Sidebar Banner (300×250)'), ('banner', 'Leaderboard Banner (728×90)'), ('sponsored', 'Sponsored Job Listing'), ('custom', 'Custom / Other')], default='sidebar', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Tell us about your business and advertising goals')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not shown to advertiser)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Inquiry',
                'verbose_name_plural': 'Ad Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
