# Generated by Django 6.0.4 on 2026-05-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_adinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adinquiry',
            name='ad_type',
            field=models.CharField(choices=[('sidebar', 'Sidebar Banner (300×250)'), ('banner', 'Leaderboard Banner (728×90)'), ('sponsored', 'Sponsored Job Listing'), ('newsletter', 'Newsletter / Email Blast'), ('brand', 'Brand Awareness / Homepage Feature'), ('product', 'Product or Service Promotion'), ('custom', 'Custom / Other')], default='sidebar', max_length=20),
        ),
    ]
