# Generated by Django 6.0.4 on 2026-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_set_site_domain'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'deadline'], name='job_active_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'is_active'], name='job_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-date_posted'], name='job_posted_idx'),
        ),
    ]
