# Generated by Django 6.0.4 on 2026-04-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('student', 'Student'), ('entry', 'Entry Level (0–2 yrs)'), ('mid', 'Mid Level (2–5 yrs)'), ('senior', 'Senior Level (5+ yrs)')], help_text='Helps us recommend the right jobs', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Your real name (shown on profile)', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='linkedin.com/in/yourprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Kathmandu, Bagmati Province', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Portfolio, GitHub or personal website'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief intro — skills, interests, goals', max_length=600),
        ),
    ]
