# Generated by Django 6.0.4 on 2026-04-19 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('excerpt', models.TextField(max_length=400)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('news', 'News'), ('tips', 'Career Tips'), ('scholarship_news', 'Scholarship Updates'), ('loksewa_update', 'Loksewa Updates'), ('foreign_news', 'Foreign Employment News')], default='news', max_length=20)),
                ('author_name', models.CharField(default='NepHub Team', max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
